import * as bodyParser from 'body-parser';
import * as cors from 'cors';
import * as express from 'express';
import * as helmet from 'helmet';
import * as morgan from 'morgan';
// ...existing code...
import logger from './utils/logger';
import { requestLogger, errorLogger } from './middlewares/logging';
import globalLimiter, { authLimiter } from './middlewares/rateLimit';
import 'reflect-metadata';
import * as swaggerJSDoc from 'swagger-jsdoc';
import * as swaggerStats from 'swagger-stats';
import * as swaggerUi from 'swagger-ui-express';
import {createConnection} from 'typeorm';
import routes from './routes';

const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
  },
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: ['**/routes/auth.ts', '**/controller/Admin/*.ts'],
};

const specs = swaggerJSDoc(options);
// Connects to the Database -> then starts the express
createConnection()
  .then(() => {
    // Create a new express application instance

    // Call midlewares
    const app = express();
  // Configure CORS: allow only origins listed in ALLOWED_ORIGINS (comma-separated)
  // If ALLOWED_ORIGINS is not set, default to localhost front-end used in docker-compose
  const allowedOriginsEnv = process.env.ALLOWED_ORIGINS || 'http://localhost:8080';
  const allowedOrigins = allowedOriginsEnv.split(',').map(s => s.trim()).filter(Boolean);
  const corsOptions: cors.CorsOptions = {
    origin: (origin, callback) => {
      // If no Origin (e.g., curl, server-to-server), allow. Browser requests will have Origin.
      if (!origin) return callback(null, true);
      if (allowedOrigins.indexOf(origin) !== -1) {
        return callback(null, true);
      }
      return callback(new Error('CORS policy: This origin is not allowed'));
    },
    methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
    allowedHeaders: ['Content-Type', 'Authorization', 'auth', 'Accept', 'X-Requested-With'],
    credentials: true,
  };
  app.use(cors(corsOptions));
  // apply basic rate limiting to all requests
  app.use(globalLimiter);
  app.use(swaggerStats.getMiddleware({}));
  app.use(helmet());
  app.use(bodyParser.json());
  // application logging
  app.use(requestLogger);
    morgan.token('header-auth', (req, res) => req.headers.auth);
    morgan.token('body', (req, res) => req.body.toString());
    app.use(morgan('[:date[web]] Started :method :url for :remote-addr', true));
    app.use(morgan('[:date[web]] Started with token :header-auth', true));
    app.use(morgan('[:date[web]] Started with body :body', true));
    app.use(
      morgan(
        '[:date[iso]] Completed :status :res[content-length] in :response-time ms',
      ),
    );
  // Set all routes from routes folder
  // Mount auth routes with a tighter rate limiter
  app.use('/auth', authLimiter, routes);
  // Mount other routes (routes should export a router where auth routes are under /auth)
  app.use('/', routes);
    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
    app.use(errorLogger);
    app.listen(3000, async () => {
      logger.info('Server started on port 3000!');
    });
  })
  .catch(e => console.log(e));
